# Markdown to XML

The purpose of this notebook is to convert my Markdown transcription of Giarratano's apparatus criticus to the XML snippet that I've settled on for the transcription format in the JSON files. I will also make the `apparatus_entry` JSON object while I'm at it.

In [56]:
import pandas as pd
import json
import re
from datetime import datetime, timezone

I manually transcribed the apparatus criticus entries for lines 14–end of Calp. Sic. 1 in Giarratano's 1910 edition. 1–13 were already done before I decided to accelerate the process with some automation. I used Markdown because it was easier for me to type than all the angle brackets for XML.

In [57]:
df = pd.read_csv('../converted-json/entries.csv')

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   line_number  204 non-null    int64
 1   lemma        198 non-null    str
 2   entry        204 non-null    str
 3   note         13 non-null     str
dtypes: int64(1), str(3)
memory usage: 6.5 KB

In [59]:
df

,line_number,lemma,entry,note
0,14,nocturnaque,"*noturnaque* G,*no^c^turnaque* N (*no^c^turna*...",NaN
1,15,pervia,*previa* P.,NaN
2,15,Fauni,"*fanni* P.,\n16,None,*O*. φεγην edd. praeter B...",NaN
3,16,calamos,*chalamos* G. versum om. b; post hunc versum B...,NaN
4,17,mea,"*mea* om. ρ (add. A in mg.), *nova* νφηθrson B...",NaN
...,...,...,...,...
199,93,sonum modulemur avena,*sono modulemur avenae* Wernsd.,NaN
200,94,forsitan,*forsitā* N.,NaN
201,94,augustas,"*angustas* Nπφρ^1^λ^1^, *agustas* μ.",NaN
202,94,Meliboeus,"*meliboeus* νε^2^ρ^2^, *melibeus* GPλπδ^1^γρ^1...",NaN
203,94,aures,"*auras* P Ulit., *auris* νφρ^2^θrsi^1^on, *ara...",NaN

Here's a function to convert the Markdown to XML.

In [98]:
def markdown_to_xml(text):
    italics = re.sub(r'\*(.*?)\*', r'<hi rend="italics">\1</hi>', text)
    superscript = re.sub(r'\^(.(.*?))\^', r'<hi rend="superscript">\1</hi>', italics)
    xml = "<ab>" + superscript + "</ab>"
    return xml

I'll make a dictionary of the Markdown transcription and XML.

In [99]:
df["xml"] = df["entry"].apply(markdown_to_xml)

In [100]:
df

,line_number,lemma,entry,note,xml,cts_id,validate
0,14,nocturnaque,"*noturnaque* G,*no^c^turnaque* N (*no^c^turna*...",NaN,"<ab><hi rend=""italics"">noturnaque</hi> G,<hi r...",urn:cts:latinLit:phi0830.phi001.dll:1.14@noctu...,True
1,15,pervia,*previa* P.,NaN,"<ab><hi rend=""italics"">previa</hi> P.</ab>",urn:cts:latinLit:phi0830.phi001.dll:1.15@pervia,True
2,15,Fauni,"*fanni* P.,\n16,None,*O*. φεγην edd. praeter B...",NaN,"<ab><hi rend=""italics"">fanni</hi> P.,\n16,None...",urn:cts:latinLit:phi0830.phi001.dll:1.15@Fauni,True
3,16,calamos,*chalamos* G. versum om. b; post hunc versum B...,NaN,"<ab><hi rend=""italics"">chalamos</hi> G. versum...",urn:cts:latinLit:phi0830.phi001.dll:1.16@calamos,True
4,17,mea,"*mea* om. ρ (add. A in mg.), *nova* νφηθrson B...",NaN,"<ab><hi rend=""italics"">mea</hi> om. ρ (add. A ...",urn:cts:latinLit:phi0830.phi001.dll:1.17@mea,True
...,...,...,...,...,...,...,...
199,93,sonum modulemur avena,*sono modulemur avenae* Wernsd.,NaN,"<ab><hi rend=""italics"">sono modulemur avenae</...",urn:cts:latinLit:phi0830.phi001.dll:1.93@sonum...,True
200,94,forsitan,*forsitā* N.,NaN,"<ab><hi rend=""italics"">forsitā</hi> N.</ab>",urn:cts:latinLit:phi0830.phi001.dll:1.94@forsitan,True
201,94,augustas,"*angustas* Nπφρ^1^λ^1^, *agustas* μ.",NaN,"<ab><hi rend=""italics"">angustas</hi> Nπφρ<hi r...",urn:cts:latinLit:phi0830.phi001.dll:1.94@augustas,True
202,94,Meliboeus,"*meliboeus* νε^2^ρ^2^, *melibeus* GPλπδ^1^γρ^1...",NaN,"<ab><hi rend=""italics"">meliboeus</hi> νε<hi re...",urn:cts:latinLit:phi0830.phi001.dll:1.94@Melib...,True
203,94,aures,"*auras* P Ulit., *auris* νφρ^2^θrsi^1^on, *ara...",NaN,"<ab><hi rend=""italics"">auras</hi> P Ulit., <hi...",urn:cts:latinLit:phi0830.phi001.dll:1.94@aures,True

In [101]:
def create_cts_id(row):
    if row['lemma'] is None or pd.isna(row['lemma']):
        return f"urn:cts:latinLit:phi0830.phi001.dll:1.{row['line_number']}@"
    else:
        return f"urn:cts:latinLit:phi0830.phi001.dll:1.{row['line_number']}@{row['lemma']}"

df["cts_id"] = df.apply(create_cts_id, axis=1)

In [102]:
df["cts_id"]

0      urn:cts:latinLit:phi0830.phi001.dll:1.14@noctu...
1        urn:cts:latinLit:phi0830.phi001.dll:1.15@pervia
2         urn:cts:latinLit:phi0830.phi001.dll:1.15@Fauni
3       urn:cts:latinLit:phi0830.phi001.dll:1.16@calamos
4           urn:cts:latinLit:phi0830.phi001.dll:1.17@mea
                             ...
199    urn:cts:latinLit:phi0830.phi001.dll:1.93@sonum...
200    urn:cts:latinLit:phi0830.phi001.dll:1.94@forsitan
201    urn:cts:latinLit:phi0830.phi001.dll:1.94@augustas
202    urn:cts:latinLit:phi0830.phi001.dll:1.94@Melib...
203       urn:cts:latinLit:phi0830.phi001.dll:1.94@aures
Name: cts_id, Length: 204, dtype: str

In [103]:
id_cts = {}

# Read json file
with open('../converted-json/calpSicPoem1-target-array.json', 'r') as f:
    data = json.load(f)
    # Loop through the array of objects and create a dictionary with id as key and cts as value
    for item in data:
        # If the apparatus_entry_id is empty, skip this item
        if "apparatus_entry_id" not in item or not item["apparatus_entry_id"]:
            continue
        else:
            id_cts[item['apparatus_entry_id']] = item['target']

In [104]:
id_cts

{'urn:uuid:f2e93fa5-f815-4ff4-92ca-adaa365f8f20': ['urn:cts:latinLit:phi0830.phi001.dll:1.1@C.'],
 'urn:uuid:37b666e6-9980-4776-81d9-d056936f49c5': ['urn:cts:latinLit:phi0830.phi001.dll:1.1@Nondum'],
 'urn:uuid:fc07310e-e32e-42f5-b6b8-7915871f71bc': ['urn:cts:latinLit:phi0830.phi001.dll:1.1@declinis'],
 'urn:uuid:c8f6d0a9-7c57-4a5e-9def-3ca62cf2e188': ['urn:cts:latinLit:phi0830.phi001.dll:1.2@quamvis'],
 'urn:uuid:7757d8c7-4980-42be-bf21-28ccf1a2659f': ['urn:cts:latinLit:phi0830.phi001.dll:1.2@praela'],
 'urn:uuid:022529cf-6b85-48c8-8dee-6b53245e3c44': ['urn:cts:latinLit:phi0830.phi001.dll:1.3'],
 'urn:uuid:4817a744-94b3-4f6c-a2ec-d57ca52daef9': ['urn:cts:latinLit:phi0830.phi001.dll:1.3@musta'],
 'urn:uuid:90c8a150-48bf-43e3-b9b2-8ae8d02b2d6f': ['urn:cts:latinLit:phi0830.phi001.dll:1.4@'],
 'urn:uuid:3f8dc9f9-4f40-4967-b101-191250643d35': ['urn:cts:latinLit:phi0830.phi001.dll:1.4@Ornyte'],
 'urn:uuid:882ea6a9-53ad-4616-a73d-7831b4cdaa8a': ['urn:cts:latinLit:phi0830.phi001.dll:1.4@vaccae'],
 'urn:uuid:e277cd21-386c-4766-8c6a-3852e41555e3': ['urn:cts:latinLit:phi0830.phi001.dll:1.5@molle sub'],
 'urn:uuid:167a8fc8-c3a8-4af7-8e61-a3c7a580d162': ['urn:cts:latinLit:phi0830.phi001.dll:1.5@hirsuta'],
 'urn:uuid:505737b6-9187-4bfc-988c-babb1cc15efe': ['urn:cts:latinLit:phi0830.phi001.dll:1.5@explicuere'],
 'urn:uuid:20714735-1595-4b9d-865a-fb071e3da43a': ['urn:cts:latinLit:phi0830.phi001.dll:1.5@genista'],
 'urn:uuid:89cb821d-1254-472b-9a9e-f1c9899357a0': ['urn:cts:latinLit:phi0830.phi001.dll:1.6@succedimus'],
 'urn:uuid:2a736434-b584-430d-b642-42d28de68370': ['urn:cts:latinLit:phi0830.phi001.dll:1.6@umbris'],
 'urn:uuid:2c98e1e5-f190-4e8f-8c63-5c0b46988aed': ['urn:cts:latinLit:phi0830.phi001.dll:1.8@O.'],
 'urn:uuid:8dc7d691-2313-4ba9-affe-18915f61b9e5': ['urn:cts:latinLit:phi0830.phi001.dll:1.8@Corydon'],
 'urn:uuid:bf201edd-3887-4459-8140-5262ce605aa7': ['urn:cts:latinLit:phi0830.phi001.dll:1.8@nemus'],
 'urn:uuid:9d0a2c08-9e17-4dc5-b987-363db1accb16': ['urn:cts:latinLit:phi0830.phi001.dll:1.8@antra-1.9@ista'],
 'urn:uuid:c81cc2aa-aed7-446d-9846-17c7e2833db9': ['urn:cts:latinLit:phi0830.phi001.dll:1.9@graciles'],
 'urn:uuid:1c86c6c2-e30a-49dc-8f75-b760bff290b4': ['urn:cts:latinLit:phi0830.phi001.dll:1.9@denset'],
 'urn:uuid:d550467b-3e48-49ce-b525-a08462de92b0': ['urn:cts:latinLit:phi0830.phi001.dll:1.10@rapidoque'],
 'urn:uuid:8b81f151-3650-4b05-8cfd-7ff4873ead67': ['urn:cts:latinLit:phi0830.phi001.dll:1.10@caput'],
 'urn:uuid:8ec8efbb-80b8-47d1-881a-c152a91d1372': ['urn:cts:latinLit:phi0830.phi001.dll:1.11@bullantes'],
 'urn:uuid:d1dbcc88-a31d-4f4c-bc25-3ca700d9d5a8': ['urn:cts:latinLit:phi0830.phi001.dll:1.11@bullantes'],
 'urn:uuid:abfa04d2-c723-4732-8274-e7efa574ff08': ['urn:cts:latinLit:phi0830.phi001.dll:1.11@ubi'],
 'urn:uuid:3c293e2c-f4a5-48e9-909c-42652fb84404': ['urn:cts:latinLit:phi0830.phi001.dll:1.12@protegit'],
 'urn:uuid:9a368dc2-c4d4-42d8-a7ed-6081b1a9dc8b': ['urn:cts:latinLit:phi0830.phi001.dll:1.12@errantibus'],
 'urn:uuid:8f6dcca4-f3a6-40ba-a6e3-b30cf94123cb': ['urn:cts:latinLit:phi0830.phi001.dll:1.13@vocas'],
 'urn:uuid:d7ac15b2-aa08-460c-bc0b-98d95be6cafb': ['urn:cts:latinLit:phi0830.phi001.dll:1.13@sequor'],
 'urn:uuid:de22d8c6-eaed-464f-a84e-901589980420': ['urn:cts:latinLit:phi0830.phi001.dll:1.13@Ornyte'],
 'urn:uuid:390d0c28-f0c2-47a7-a75d-f0fd1b9d5601': ['urn:cts:latinLit:phi0830.phi001.dll:1.13@Leuce'],
 'urn:uuid:9de244d4-7413-47c6-a20d-ddc6c86ddefc': ['urn:cts:latinLit:phi0830.phi001.dll:1.14@nocturnaque'],
 'urn:uuid:bc016a02-5c44-4fc2-8b56-9273dc2e2bfd': ['urn:cts:latinLit:phi0830.phi001.dll:1.15@pervia'],
 'urn:uuid:059560c1-2d15-4988-8320-0b81080d38a8': ['urn:cts:latinLit:phi0830.phi001.dll:1.15@Fauni'],
 'urn:uuid:0380e1d1-ab68-4b6d-855d-89803f846b88': ['urn:cts:latinLit:phi0830.phi001.dll:1.16@prome igitur calamos et si qua recondita servas;'],
 'urn:uuid:ac90f88d-aeb8-4389-ba83-b85092f1bfd8': ['urn:cts:latinLit:phi0830.phi001.dll:1.16@'],
 'urn:uuid:57e3c173-eb80-46e2-bc35-9370b845300b': ['urn:cts:latinLit:phi0830.phi001.dll:1.16@calamos'],
 'urn:uuid:e2a07fea-bec4-4ffc-95d6-7c6400f35a5a': ['urn:cts:latinLit:phi0830.phi001.dll:1.17@mea'],
 'urn:uuid:d8e1822f-c44f-4bb1-9a2a-5021c88d85ee': ['urn:cts:latinLit:phi0830.phi001.dll:1.18@matura'],
 'urn:uuid:0ea128a6-7be0-4593-b782-6155e24fefa8': ['urn:cts:latinLit:phi0830.phi001.dll:1.18@docilis'],
 'urn:uuid:effb1c79-6a78-4e71-b67f-94b28ab66e88': ['urn:cts:latinLit:phi0830.phi001.dll:1.18@arundine'],
 'urn:uuid:b83e6c2c-6a51-4504-bf55-ca6fec68405a': ['urn:cts:latinLit:phi0830.phi001.dll:1.18@Ladon'],
 'urn:uuid:1bf943f0-c283-40f1-9a55-4c684199c699': ['urn:cts:latinLit:phi0830.phi001.dll:1.19@O.'],
 'urn:uuid:c49e785b-e564-482a-9348-8da3092c0adf': ['urn:cts:latinLit:phi0830.phi001.dll:1.19@Et'],
 'urn:uuid:4be00ecf-ecdc-4e5e-ba79-3dc9c3ea12ff': ['urn:cts:latinLit:phi0830.phi001.dll:1.19@captatae'],
 'urn:uuid:33791abe-8c8d-4e73-b219-620bc198e39b': ['urn:cts:latinLit:phi0830.phi001.dll:1.19@pariter'],
 'urn:uuid:854c71f8-acd2-4a65-8ea9-5ff122c2526c': ['urn:cts:latinLit:phi0830.phi001.dll:1.19@successimus'],
 'urn:uuid:772b55bf-f27f-4016-8452-e2a8a7064c42': ['urn:cts:latinLit:phi0830.phi001.dll:1.20@'],
 'urn:uuid:2f7cb4ea-0925-4eab-a04c-1cc3911853b5': ['urn:cts:latinLit:phi0830.phi001.dll:1.20@sacra'],
 'urn:uuid:6d520f71-005e-4a97-838c-714d708ae8fe': ['urn:cts:latinLit:phi0830.phi001.dll:1.20@descripta'],
 'urn:uuid:50b010cd-b110-422d-9e53-1dbb26f644d1': ['urn:cts:latinLit:phi0830.phi001.dll:1.20@est'],
 'urn:uuid:550c3b9a-2bf4-49b5-92aa-d71c880b912f': ['urn:cts:latinLit:phi0830.phi001.dll:1.21@quis'],
 'urn:uuid:14406301-778b-4580-ac52-816bab786387': ['urn:cts:latinLit:phi0830.phi001.dll:1.22@'],
 'urn:uuid:fe313331-663a-4a86-8022-1ab03a5e9759': ['urn:cts:latinLit:phi0830.phi001.dll:1.22@aspicis'],
 'urn:uuid:32db9dfb-2538-4970-b83c-f5aea9648c6b': ['urn:cts:latinLit:phi0830.phi001.dll:1.22@nunc'],
 'urn:uuid:c8f512c7-9c9d-44e8-bbde-ffd9d91679ef': ['urn:cts:latinLit:phi0830.phi001.dll:1.22@littera'],
 'urn:uuid:6411281c-c591-4f89-8401-caa3ff4c0dbd': ['urn:cts:latinLit:phi0830.phi001.dll:1.23@servet'],
 'urn:uuid:bd21ded0-636a-4857-9d26-a5f717a3ce28': ['urn:cts:latinLit:phi0830.phi001.dll:1.23@arenti'],
 'urn:uuid:64de5bba-d578-493d-b9c3-0c52b33dd155': ['urn:cts:latinLit:phi0830.phi001.dll:1.23@se laxet'],
 'urn:uuid:c52cb9ad-6382-4785-a52b-5e3a8f30d9cd': ['urn:cts:latinLit:phi0830.phi001.dll:1.23@hiatu'],
 'urn:uuid:5a773724-9732-4baa-a1e7-6ce6c8d3f400': ['urn:cts:latinLit:phi0830.phi001.dll:1.24@C.'],
 'urn:uuid:f1cf2ae2-a2c1-4e30-93ca-f0178ce8d581': ['urn:cts:latinLit:phi0830.phi001.dll:1.24@Ornyte'],
 'urn:uuid:87220fb7-7deb-467a-b32f-0ccd53c537b5': ['urn:cts:latinLit:phi0830.phi001.dll:1.24@propius'],
 'urn:uuid:b61264a3-94b9-44ea-9a2a-5a84cc652da4': ['urn:cts:latinLit:phi0830.phi001.dll:1.24@tua'],
 'urn:uuid:1b31c779-e056-4b91-b83a-e482f370015d': ['urn:cts:latinLit:phi0830.phi001.dll:1.24@alto'],
 'urn:uuid:81fbfdad-5999-42ff-ade9-5bde4dd90b12': ['urn:cts:latinLit:phi0830.phi001.dll:1.25@cortice'],
 'urn:uuid:d2d78ce8-ae8b-4e6f-be2b-e8b21ea4fce2': ['urn:cts:latinLit:phi0830.phi001.dll:1.25@descriptos'],
 'urn:uuid:935669b5-28b5-4fb5-8926-fc789fbda482': ['urn:cts:latinLit:phi0830.phi001.dll:1.25@citius percurrere versus'],
 'urn:uuid:9c606485-9dad-43a4-b53c-aee69081ebb6': ['urn:cts:latinLit:phi0830.phi001.dll:1.25@citius'],
 'urn:uuid:d634628b-b09e-4330-975a-e9aaa19a4012': ['urn:cts:latinLit:phi0830.phi001.dll:1.25@percurrere'],
 'urn:uuid:07e5c40b-02fd-46e8-ab27-60351dbaa2e6': ['urn:cts:latinLit:phi0830.phi001.dll:1.26@'],
 'urn:uuid:1853bd38-7e18-417b-8615-3a9430ab100c': ['urn:cts:latinLit:phi0830.phi001.dll:1.26@nam'],
 'urn:uuid:8521c41b-2ed8-41b7-a338-857bd09b40fa': ['urn:cts:latinLit:phi0830.phi001.dll:1.28@O.'],
 'urn:uuid:6c64e77b-3e45-4888-8b59-7f20df87b005': ['urn:cts:latinLit:phi0830.phi001.dll:1.28@haec'],
 'urn:uuid:f84cd3ef-212a-438e-a23a-4d9d6f32c1f9': ['urn:cts:latinLit:phi0830.phi001.dll:1.28@triviali'],
 'urn:uuid:9b5a67a3-2474-401d-86c4-7d2328ccd703': ['urn:cts:latinLit:phi0830.phi001.dll:1.29@nihil armentale'],
 'urn:uuid:ed6ba4ea-fe89-4dc7-93a4-208964a2f882': ['urn:cts:latinLit:phi0830.phi001.dll:1.29@resultat'],
 'urn:uuid:45b8835d-dde7-4946-9763-7079f603bdd6': ['urn:cts:latinLit:phi0830.phi001.dll:1.30'],
 'urn:uuid:359d06cb-eeb5-4524-904a-8bb7051d03a3': ['urn:cts:latinLit:phi0830.phi001.dll:1.30@nec'],
 'urn:uuid:81aba24f-dc5e-41d7-b43a-91bf52c41dd8': ['urn:cts:latinLit:phi0830.phi001.dll:1.30@distinguunt'],
 'urn:uuid:97e75384-4939-4892-97a2-7a5a4bb52abc': ['urn:cts:latinLit:phi0830.phi001.dll:1.30@iubila'],
 'urn:uuid:c848207e-09f6-4f9a-8911-0b4f07823231': ['urn:cts:latinLit:phi0830.phi001.dll:1.33@O.'],
 'urn:uuid:6d14a91d-8cf8-45dd-a8b1-b2443caa1936': ['urn:cts:latinLit:phi0830.phi001.dll:1.33@tueor'],
 'urn:uuid:36ec6184-a14d-4f6d-81e8-2b905ca817b8': ['urn:cts:latinLit:phi0830.phi001.dll:1.35@patefactis'],
 'urn:uuid:f0496525-8ac1-4bdd-a164-ee865584ea05': ['urn:cts:latinLit:phi0830.phi001.dll:1.35@fatis'],
 'urn:uuid:f8b3ea41-1208-43d5-8313-9a09bbf8c574': ['urn:cts:latinLit:phi0830.phi001.dll:1.36@gaudete'],
 'urn:uuid:fcf616cc-44e5-46bb-a6d5-d88543ec18ee': ['urn:cts:latinLit:phi0830.phi001.dll:1.38@pecus'],
 'urn:uuid:12b42fde-13c6-40af-bc0b-fd31069ed575': ['urn:cts:latinLit:phi0830.phi001.dll:1.38@nocturnaque'],
 'urn:uuid:93387c7b-3bd0-4e55-a454-efc5f7cded58': ['urn:cts:latinLit:phi0830.phi001.dll:1.39@fraxinea'],
 'urn:uuid:ef6182bb-4524-4cdb-aa7a-6004c2bd900d': ['urn:cts:latinLit:phi0830.phi001.dll:1.39@nolit'],
 'urn:uuid:ddf25f0a-7a8d-41b1-ad49-0b818f8a41c9': ['urn:cts:latinLit:phi0830.phi001.dll:1.39@praesaepia'],
 'urn:uuid:e7aca54d-004c-4d57-bd32-1728858eed68': ['urn:cts:latinLit:phi0830.phi001.dll:1.40@insidias'],
 'urn:uuid:1e9a0772-e2c5-4889-a84f-ed339c6bc459': ['urn:cts:latinLit:phi0830.phi001.dll:1.40@ovilibus'],
 'urn:uuid:26f2a2da-8f20-43a2-9357-61d65e32038b': ['urn:cts:latinLit:phi0830.phi001.dll:1.41@afferet'],
 'urn:uuid:42de66cd-0bc8-461b-a4fa-f28c61e44790': ['urn:cts:latinLit:phi0830.phi001.dll:1.41@abiget'],
 'urn:uuid:7b97350f-adf2-48be-9952-063d153a55f7': ['urn:cts:latinLit:phi0830.phi001.dll:1.42@aurea secura cum pace renascitur aetas'],
 'urn:uuid:eb66d907-0094-4657-8a14-6fbabf1e667a': ['urn:cts:latinLit:phi0830.phi001.dll:1.42@secura'],
 'urn:uuid:b7be3397-80ef-457e-999e-de8123c9d6fa': ['urn:cts:latinLit:phi0830.phi001.dll:1.42@cum'],
 'urn:uuid:d31baa5b-2fe5-4260-844d-e094d03f1fa3': ['urn:cts:latinLit:phi0830.phi001.dll:1.42@pace'],
 'urn:uuid:f40e6583-0731-400d-9b93-901b1ef784e7': ['urn:cts:latinLit:phi0830.phi001.dll:1.43@redit'],
 'urn:uuid:cf65cd1b-b158-4d7e-95ec-cb38247bd625': ['urn:cts:latinLit:phi0830.phi001.dll:1.43@tandem squalore'],
 'urn:uuid:170dc9d1-d5fe-4dbf-ad3d-4da26f047646': ['urn:cts:latinLit:phi0830.phi001.dll:1.43@tandem'],
 'urn:uuid:569bd228-8f9e-43bd-be5f-27a66cf6c250': ['urn:cts:latinLit:phi0830.phi001.dll:1.44@Themis'],
 'urn:uuid:29bb3403-834d-4c78-9918-0a7964c68f98': ['urn:cts:latinLit:phi0830.phi001.dll:1.44@sequuntur'],
 'urn:uuid:a23807bf-6bea-49c0-bede-6803d7d4d788': ['urn:cts:latinLit:phi0830.phi001.dll:1.45@maternis'],
 'urn:uuid:0604f7a3-e082-482e-b79f-bf11ca3661c6': ['urn:cts:latinLit:phi0830.phi001.dll:1.45@causam'],
 'urn:uuid:871369c8-25cb-4332-ae1b-5f7379e76323': ['urn:cts:latinLit:phi0830.phi001.dll:1.45@vicit'],
 'urn:uuid:977ed666-3756-4d91-9f2d-d7fe490c75f3': ['urn:cts:latinLit:phi0830.phi001.dll:1.45@Iulis'],
 'urn:uuid:78dce368-659d-4350-bdfd-5396ae60437f': ['urn:cts:latinLit:phi0830.phi001.dll:1.46@populos'],
 'urn:uuid:bc439016-5d16-4b3d-9bb7-2749ca42e4d1': ['urn:cts:latinLit:phi0830.phi001.dll:1.46@deus'],
 'urn:uuid:8109ad57-be5f-4059-94db-9c9bf5d3d67b': ['urn:cts:latinLit:phi0830.phi001.dll:1.46@dabit'],
 'urn:uuid:7117e573-2160-4a1b-a1b9-d9449bc42205': ['urn:cts:latinLit:phi0830.phi001.dll:1.46@vinctas'],
 'urn:uuid:238ae430-132f-4149-985c-41876f9b452e': ['urn:cts:latinLit:phi0830.phi001.dll:1.47@post tergum'],
 'urn:uuid:9521cbdc-261b-49a1-916b-db89c68fc014': ['urn:cts:latinLit:phi0830.phi001.dll:1.48@vesanos'],
 'urn:uuid:5e0b8361-69af-4870-91f1-286cd9be8260': ['urn:cts:latinLit:phi0830.phi001.dll:1.48@torquebit'],
 'urn:uuid:8c65e711-d782-4e36-8597-24ae814c59a4': ['urn:cts:latinLit:phi0830.phi001.dll:1.48@morsus'],
 'urn:uuid:8ce8da74-3d62-4b38-ac78-a6bc2a5e34aa': ['urn:cts:latinLit:phi0830.phi001.dll:1.49@quae'],
 'urn:uuid:61b55106-42ff-4c7c-860c-4dd6a8d9e662': ['urn:cts:latinLit:phi0830.phi001.dll:1.50@Philippos'],
 'urn:uuid:f856080e-56f6-4a74-a045-dcbc1f5339c1': ['urn:cts:latinLit:phi0830.phi001.dll:1.51@deflebit, nullos ducet captiva triumphos;'],
 'urn:uuid:b5ba7607-e95c-464e-b620-f3c89617dac8': ['urn:cts:latinLit:phi0830.phi001.dll:1.51@deflebit'],
 'urn:uuid:bf9a7a3f-e6b6-40f9-b109-516575b716da': ['urn:cts:latinLit:phi0830.phi001.dll:1.51@nullos ducet'],
 'urn:uuid:b8b65f48-c6a5-497c-8108-70fc466b697e': ['urn:cts:latinLit:phi0830.phi001.dll:1.51@triumphos'],
 'urn:uuid:d2900cbf-7a57-4a2e-8d4a-749621ecd6f8': ['urn:cts:latinLit:phi0830.phi001.dll:1.52@subigentur'],
 'urn:uuid:33f5ff46-39db-45e2-a67e-d57c7a744802': ['urn:cts:latinLit:phi0830.phi001.dll:1.52@carcere'],
 'urn:uuid:769ca300-38ab-494c-91db-c5bc0f819da7': ['urn:cts:latinLit:phi0830.phi001.dll:1.52@bella'],
 'urn:uuid:d2e429f0-022d-4641-976e-e513a0b0c9f6': ['urn:cts:latinLit:phi0830.phi001.dll:1.53@inmergentque'],
 'urn:uuid:a08c1189-ccd1-4454-8f69-17fb3cd38233': ['urn:cts:latinLit:phi0830.phi001.dll:1.53@caput'],
 'urn:uuid:258fe779-783b-488c-8cdb-bd287505630b': ['urn:cts:latinLit:phi0830.phi001.dll:1.53@tenebris'],
 'urn:uuid:87218101-d4fe-49b3-b645-8ebbd34b6c87': ['urn:cts:latinLit:phi0830.phi001.dll:1.54@nec'],
 'urn:uuid:40d38ab4-ad3a-4abe-98e2-27d716974cb5': ['urn:cts:latinLit:phi0830.phi001.dll:1.54@vultu'],
 'urn:uuid:41239854-6502-43fb-a7ad-7429f6e7558d': ['urn:cts:latinLit:phi0830.phi001.dll:1.55@qualis saepe fuit, quae libera Marte professo,'],
 'urn:uuid:7ae6a99d-1ac1-499e-847f-283b984dd903': ['urn:cts:latinLit:phi0830.phi001.dll:1.55@qualis'],
 'urn:uuid:b9262f6c-213b-4aaf-93d9-c38152a2eec1': ['urn:cts:latinLit:phi0830.phi001.dll:1.55@quae'],
 'urn:uuid:bedc3436-32af-4a77-8cc9-c1eba24ccbe7': ['urn:cts:latinLit:phi0830.phi001.dll:1.55@Marte'],
 'urn:uuid:6d370564-2365-4aa0-b6bf-7a60f436c2fe': ['urn:cts:latinLit:phi0830.phi001.dll:1.55@professo'],
 'urn:uuid:999123f0-5797-436f-a2f2-538d0c1df8b8': ['urn:cts:latinLit:phi0830.phi001.dll:1.56@quae'],
 'urn:uuid:d5e2ecfe-ca85-405c-b070-c310a2b9e511': ['urn:cts:latinLit:phi0830.phi001.dll:1.56@tamen'],
 'urn:uuid:5a107be6-3b0e-4f97-8a26-be01f28df06f': ['urn:cts:latinLit:phi0830.phi001.dll:1.56@grassantibus'],
 'urn:uuid:14b8eb7c-8517-4ac4-946d-924979f2c7d1': ['urn:cts:latinLit:phi0830.phi001.dll:1.57@publica'],
 'urn:uuid:55734acc-3756-4b96-8a84-eed14ff5fd91': ['urn:cts:latinLit:phi0830.phi001.dll:1.57@diffudit'],
 'urn:uuid:dde31f24-8ecd-40e4-878f-d79c5286b89b': ['urn:cts:latinLit:phi0830.phi001.dll:1.57@tacito'],
 'urn:uuid:d6495508-9998-4e07-953f-10599783e0ee': ['urn:cts:latinLit:phi0830.phi001.dll:1.57@discordia'],
 'urn:uuid:3e72d73b-2f5f-469b-b053-1ffa42edcb6c': ['urn:cts:latinLit:phi0830.phi001.dll:1.59@insanos'],
 'urn:uuid:775c812e-b075-4b90-917b-5fcc0bc88548': ['urn:cts:latinLit:phi0830.phi001.dll:1.59@Clementia'],
 'urn:uuid:4aeeb502-726e-4d01-a1a9-15b4d597ff9c': ['urn:cts:latinLit:phi0830.phi001.dll:1.59@contudit'],
 'urn:uuid:4101d9c1-fae9-4d06-8faa-096414f53bfc': ['urn:cts:latinLit:phi0830.phi001.dll:1.60@catenati'],
 'urn:uuid:bdadb357-d338-4bf7-ba01-d5bad81b0ef8': ['urn:cts:latinLit:phi0830.phi001.dll:1.60@senatus'],
 'urn:uuid:5e463bf9-9c3b-4999-97e2-4899b005a83b': ['urn:cts:latinLit:phi0830.phi001.dll:1.61@lassabit'],
 'urn:uuid:1ee51180-8088-4601-ba20-76cf0a21793a': ['urn:cts:latinLit:phi0830.phi001.dll:1.61@pleno'],
 'urn:uuid:ddaaaa67-62da-4205-99e9-929aa741db68': ['urn:cts:latinLit:phi0830.phi001.dll:1.62@numerabit'],
 'urn:uuid:9e7bb04f-2048-4e15-8240-3a9f54e2bad6': ['urn:cts:latinLit:phi0830.phi001.dll:1.63@quae stricti'],
 'urn:uuid:fba7a082-6b34-4bfa-9749-01c0ff517604': ['urn:cts:latinLit:phi0830.phi001.dll:1.64@referet'],
 'urn:uuid:2e5e2c03-f315-42d9-9772-306b0a4e953f': ['urn:cts:latinLit:phi0830.phi001.dll:1.64@Latialia'],
 'urn:uuid:b3685908-cf85-42ac-8e2d-81aa4b4f91ca': ['urn:cts:latinLit:phi0830.phi001.dll:1.65@qui'],
 'urn:uuid:2f8cfb8f-58a8-4152-aa47-4002231bb0f5': ['urn:cts:latinLit:phi0830.phi001.dll:1.65@primus'],
 'urn:uuid:eac84834-51b2-487e-a4f9-de9a19129913': ['urn:cts:latinLit:phi0830.phi001.dll:1.65@caede'],
 'urn:uuid:2bb5cb33-bd55-4f4f-b554-59e0ba0e84f0': ['urn:cts:latinLit:phi0830.phi001.dll:1.66@ardentia'],
 'urn:uuid:1ab266ac-0997-4f53-a243-b59a1b8fcbf8': ['urn:cts:latinLit:phi0830.phi001.dll:1.67@docuit'],
 'urn:uuid:37f926d2-c953-4d90-ba76-928a8e4afba7': ['urn:cts:latinLit:phi0830.phi001.dll:1.68@inter[1]',
  'urn:cts:latinLit:phi0830.phi001.dll:1.68@inter[2]'],
 'urn:uuid:c4a0fe49-eef8-401c-8fc6-aff5a39a5c87': ['urn:cts:latinLit:phi0830.phi001.dll:1.70@vacuos'],
 'urn:uuid:0b01ddfd-9fda-4ac2-a05f-0dfff45fa9da': ['urn:cts:latinLit:phi0830.phi001.dll:1.70@fasces'],
 'urn:uuid:814b01ce-26ad-4fa4-b855-b106ea2ab662': ['urn:cts:latinLit:phi0830.phi001.dll:1.71@et inane'],
 'urn:uuid:bc76663a-fa90-44a2-ad61-6dab089c0a0c': ['urn:cts:latinLit:phi0830.phi001.dll:1.71@reductis'],
 'urn:uuid:1cfcb51e-d6d7-47c4-a944-294816a681b7': ['urn:cts:latinLit:phi0830.phi001.dll:1.72@vultumque priorem'],
 'urn:uuid:42ab9626-d180-4f38-b66e-cc0795a7f54b': ['urn:cts:latinLit:phi0830.phi001.dll:1.73@auferet'],
 'urn:uuid:c8ba7e29-9a92-467f-8417-30d8e54d94aa': ['urn:cts:latinLit:phi0830.phi001.dll:1.74@exsultet'],
 'urn:uuid:755f0a48-b0c2-4a66-9888-a725adc5d4a4': ['urn:cts:latinLit:phi0830.phi001.dll:1.74@quaecumque'],
 'urn:uuid:415f78c3-5634-4117-b2ce-bc1fab969157': ['urn:cts:latinLit:phi0830.phi001.dll:1.74@notum'],
 'urn:uuid:7d6209b4-3c82-42d8-a555-ecd1b6c2e6fc': ['urn:cts:latinLit:phi0830.phi001.dll:1.74@gens'],
 'urn:uuid:5af7fc7e-a33f-4004-ba1b-30347c373f0d': ['urn:cts:latinLit:phi0830.phi001.dll:1.74@ima'],
 'urn:uuid:9072d907-9d6f-4ff7-b009-a8a2a47c78b0': ['urn:cts:latinLit:phi0830.phi001.dll:1.74@iacentem'],
 'urn:uuid:13798576-2d20-44c2-8f74-c3f3926cebd5': ['urn:cts:latinLit:phi0830.phi001.dll:1.75@erectumve'],
 'urn:uuid:f24a83f5-eb43-403f-b3c6-39e784c69d43': ['urn:cts:latinLit:phi0830.phi001.dll:1.75@boream'],
 'urn:uuid:9c459f04-e5f3-4849-8d35-1c0ade05d1e1': ['urn:cts:latinLit:phi0830.phi001.dll:1.75@quaecumque'],
 'urn:uuid:bc5fd516-6b26-4a37-ade6-8a5f52fdfa21': ['urn:cts:latinLit:phi0830.phi001.dll:1.76@patet'],
 'urn:uuid:1723d4f7-d508-40ca-a4a7-e01dfed5a86d': ['urn:cts:latinLit:phi0830.phi001.dll:1.76@mediove'],
 'urn:uuid:8f70f7b7-8a7f-49f8-bd6a-57c1434dafe4': ['urn:cts:latinLit:phi0830.phi001.dll:1.76@fervit'],
 'urn:uuid:62f8fca0-5618-4778-bb8d-a4b07532cf17': ['urn:cts:latinLit:phi0830.phi001.dll:1.77@vicesima'],
 'urn:uuid:3ac14a8e-a488-4ce9-842b-6e35d9f189ee': ['urn:cts:latinLit:phi0830.phi001.dll:1.78@fulgeat'],
 'urn:uuid:31704f5d-42f8-4a6e-a550-204af6197f86': ['urn:cts:latinLit:phi0830.phi001.dll:1.78@et placida radiantem'],
 'urn:uuid:2f0c836e-a90a-41c8-81e2-250be8fe2c5d': ['urn:cts:latinLit:phi0830.phi001.dll:1.78@cometem'],
 'urn:uuid:b5ff10c2-a259-4464-a68c-7ff1fdea4a2b': ['urn:cts:latinLit:phi0830.phi001.dll:1.79@proferat'],
 'urn:uuid:b8b0a1da-e37c-4b6b-9e23-4144bff9ce39': ['urn:cts:latinLit:phi0830.phi001.dll:1.79@niteat'],
 'urn:uuid:a26ffb58-a488-436d-854d-b7dd28091413': ['urn:cts:latinLit:phi0830.phi001.dll:1.79@sidus'],
 'urn:uuid:47d7c870-9f74-4193-9528-770c46617032': ['urn:cts:latinLit:phi0830.phi001.dll:1.80@numquid'],
 'urn:uuid:0cd4efb4-cec9-40c1-b344-b59a10e359fd': ['urn:cts:latinLit:phi0830.phi001.dll:1.80@utrumque'],
 'urn:uuid:8b29b6c9-1bdb-4020-86c7-b11a7fe74485': ['urn:cts:latinLit:phi0830.phi001.dll:1.80@sicut'],
 'urn:uuid:15c37ba4-59c6-479c-8bef-0d138832c245': ['urn:cts:latinLit:phi0830.phi001.dll:1.80@cruento'],

In [105]:
cts = [" ".join(v) for k, v in id_cts.items()]

In [106]:
df["validate"] = df["cts_id"].apply(lambda x: x in cts)

In [107]:
df["validate"].value_counts()

validate
True     194
False     10
Name: count, dtype: int64

In [108]:
false_entries = df[df["validate"] == False].copy()

In [109]:
for id in false_entries["cts_id"]:
    print(id)

urn:cts:latinLit:phi0830.phi001.dll:1.23@se
urn:cts:latinLit:phi0830.phi001.dll:1.30@nec montana sacros distinguunt iubila versus.
urn:cts:latinLit:phi0830.phi001.dll:1.31@
urn:cts:latinLit:phi0830.phi001.dll:1.31@C.
urn:cts:latinLit:phi0830.phi001.dll:1.31@oculoque
urn:cts:latinLit:phi0830.phi001.dll:1.31@sequaci
urn:cts:latinLit:phi0830.phi001.dll:1.32@perlege
urn:cts:latinLit:phi0830.phi001.dll:1.57@
urn:cts:latinLit:phi0830.phi001.dll:1.68@inter-inter
urn:cts:latinLit:phi0830.phi001.dll:1.87@nec prius ex meritis defunctos Roma penates

In [110]:
df.to_csv('../converted-json/entries_with_cts5.csv', index=False)